### ISSUE TITLE
inaccurate 

### ISSUE THREAD

**Issue by staarmaan** [Permdog99/Legacy-Reborn#1]
the font, the logo, the crafting menu, the sky, the world gui are all inaccurate
and when you hit a mob it doesnt wobble like in the actual tu1

**Comment by staarmaan** [comment]
and the skeletons as well i think

**Comment by Permdog99** [comment]
With the crafting menu, I cannot remove the tabs from Legacy4J until a GUI API is added. This is the same with removing other things of the GUI.

The logo is something I am working on, but it will not say "Xbox 360", but rather "Console Edition"

This modpack is designed as "what if TU1 and other TUs were polished and put on other consoles". While I think the janky GUI, bugs, and glitches would be accurate, I do not see it wise to add them and call it "polished".

Also the GUI assets that were used on Xbox 360 from TU1 to some time after TU24 were not used on other platforms. The assets were replaced with less janky ones. Because of this, I believe that if TU1 to TU12 were added to other platforms, they would also use these newer assets. After all, 4J Studios was pushed by the community to release the game early 

I may add some of the jank in the future, but the goal is to make things more polished while staying accurate.

**Comment by Permdog99** [comment]
Closing this issue as most in inaccuracies listed will be fixed in 1.3
